/* Auto-generated by scripts/gen_uart_tx_vectors.py. Do not edit manually. */
`ifndef UART_TX_TEST_VECTORS_SVH
`define UART_TX_TEST_VECTORS_SVH

// Stop bits: 1
// Vectores por modo: 6 smoke + 9 random = 15 x 3 modos = 45 total

// ========== Parity mode: NONE ==========
localparam int NUM_SMOKE_NONE = 6;
localparam int NUM_RANDOM_NONE = 9;

logic [7:0] smoke_data_none  [0:NUM_SMOKE_NONE-1];
initial begin
    smoke_data_none[0] = 8'h1F; // BASIC_1F
    smoke_data_none[1] = 8'h00; // ALL_ZERO
    smoke_data_none[2] = 8'h80; // MSB_SET
    smoke_data_none[3] = 8'hFF; // ALL_ONES
    smoke_data_none[4] = 8'h55; // ALT_55
    smoke_data_none[5] = 8'hAA; // ALT_AA
end

logic [7:0] random_data_none  [0:NUM_RANDOM_NONE-1];
initial begin
    // Reutilizamos datos existentes para mantener diversidad
    random_data_none[0] = 8'hAD; // RND_0
    random_data_none[1] = 8'hF9; // RND_1
    random_data_none[2] = 8'h34; // RND_2
    random_data_none[3] = 8'h4D; // RND_3
    random_data_none[4] = 8'hBB; // RND_4
    random_data_none[5] = 8'hC1; // RND_5
    random_data_none[6] = 8'h08; // RND_6
    random_data_none[7] = 8'h93; // RND_7
    random_data_none[8] = 8'hF6; // RND_8
end

// ========== Parity mode: EVEN ==========
localparam int NUM_SMOKE_EVEN = 6;
localparam int NUM_RANDOM_EVEN = 9;

logic [7:0] smoke_data_even  [0:NUM_SMOKE_EVEN-1];
initial begin
    smoke_data_even[0] = 8'h1F; // BASIC_1F
    smoke_data_even[1] = 8'h00; // ALL_ZERO
    smoke_data_even[2] = 8'h80; // MSB_SET
    smoke_data_even[3] = 8'hFF; // ALL_ONES
    smoke_data_even[4] = 8'h55; // ALT_55
    smoke_data_even[5] = 8'hAA; // ALT_AA
end

logic [7:0] random_data_even  [0:NUM_RANDOM_EVEN-1];
initial begin
    random_data_even[0] = 8'hF5; // RND_0
    random_data_even[1] = 8'hAA; // RND_1
    random_data_even[2] = 8'hA7; // RND_2
    random_data_even[3] = 8'h2E; // RND_3
    random_data_even[4] = 8'hAD; // RND_4
    random_data_even[5] = 8'h59; // RND_5
    random_data_even[6] = 8'hCF; // RND_6
    random_data_even[7] = 8'hFD; // RND_7
    random_data_even[8] = 8'hD9; // RND_8
end

// ========== Parity mode: ODD ==========
localparam int NUM_SMOKE_ODD = 6;
localparam int NUM_RANDOM_ODD = 9;

logic [7:0] smoke_data_odd  [0:NUM_SMOKE_ODD-1];
initial begin
    smoke_data_odd[0] = 8'h1F; // BASIC_1F
    smoke_data_odd[1] = 8'h00; // ALL_ZERO
    smoke_data_odd[2] = 8'h80; // MSB_SET
    smoke_data_odd[3] = 8'hFF; // ALL_ONES
    smoke_data_odd[4] = 8'h55; // ALT_55
    smoke_data_odd[5] = 8'hAA; // ALT_AA
end

logic [7:0] random_data_odd  [0:NUM_RANDOM_ODD-1];
initial begin
    random_data_odd[0] = 8'hEA; // RND_0
    random_data_odd[1] = 8'hB4; // RND_1
    random_data_odd[2] = 8'hA7; // RND_2
    random_data_odd[3] = 8'h94; // RND_3
    random_data_odd[4] = 8'hA5; // RND_4
    random_data_odd[5] = 8'h0C; // RND_5
    random_data_odd[6] = 8'hD4; // RND_6
    random_data_odd[7] = 8'hE9; // RND_7
    random_data_odd[8] = 8'h2C; // RND_8
end

`endif // UART_TX_TEST_VECTORS_SVH
