/* Auto-generated by scripts/gen_uart_rx_vectors.py. Do not edit manually. */
`ifndef UART_RX_TEST_VECTORS_SVH
`define UART_RX_TEST_VECTORS_SVH

// Stop bits: 1
// Vectores por modo: 6 smoke + 9 random + error cases
// - NONE: 15 valid + 1 frame_err = 16 total
// - EVEN/ODD: 15 valid + 1 parity_err + 1 frame_err = 17 total
// Total: 16 + 17 + 17 = 50 vectores

// ========== Parity mode: NONE (frame bits: 10) ==========
localparam int NUM_SMOKE_NONE = 6;
localparam int NUM_RANDOM_NONE = 9;
localparam int NUM_ERROR_NONE = 1;
localparam int FRAME_BITS_NONE = 10;

logic [7:0] smoke_data_none [0:NUM_SMOKE_NONE-1];
logic [10:0] smoke_frame_none [0:NUM_SMOKE_NONE-1];

initial begin
    smoke_data_none[0] = 8'h1F; // BASIC_1F
    smoke_frame_none[0] = 11'h23E; // BASIC_1F
    smoke_data_none[1] = 8'h00; // ALL_ZERO
    smoke_frame_none[1] = 11'h200; // ALL_ZERO
    smoke_data_none[2] = 8'h80; // MSB_SET
    smoke_frame_none[2] = 11'h300; // MSB_SET
    smoke_data_none[3] = 8'hFF; // ALL_ONES
    smoke_frame_none[3] = 11'h3FE; // ALL_ONES
    smoke_data_none[4] = 8'h55; // ALT_55
    smoke_frame_none[4] = 11'h2AA; // ALT_55
    smoke_data_none[5] = 8'hAA; // ALT_AA
    smoke_frame_none[5] = 11'h354; // ALT_AA
end

logic [7:0] random_data_none [0:NUM_RANDOM_NONE-1];
logic [10:0] random_frame_none [0:NUM_RANDOM_NONE-1];

initial begin
    random_data_none[0] = 8'hE1; // RND_0
    random_frame_none[0] = 11'h3C2; // RND_0
    random_data_none[1] = 8'h3B; // RND_1
    random_frame_none[1] = 11'h276; // RND_1
    random_data_none[2] = 8'h03; // RND_2
    random_frame_none[2] = 11'h206; // RND_2
    random_data_none[3] = 8'h2E; // RND_3
    random_frame_none[3] = 11'h25C; // RND_3
    random_data_none[4] = 8'h11; // RND_4
    random_frame_none[4] = 11'h222; // RND_4
    random_data_none[5] = 8'h2A; // RND_5
    random_frame_none[5] = 11'h254; // RND_5
    random_data_none[6] = 8'h32; // RND_6
    random_frame_none[6] = 11'h264; // RND_6
    random_data_none[7] = 8'hB5; // RND_7
    random_frame_none[7] = 11'h36A; // RND_7
    random_data_none[8] = 8'h79; // RND_8
    random_frame_none[8] = 11'h2F2; // RND_8
end

logic [7:0] error_data_none [0:NUM_ERROR_NONE-1];
logic [10:0] error_frame_none [0:NUM_ERROR_NONE-1];
logic error_parity_flag_none [0:NUM_ERROR_NONE-1];
logic error_frame_flag_none [0:NUM_ERROR_NONE-1];

initial begin
    error_data_none[0] = 8'h99; // FERR
    error_frame_none[0] = 11'h132; // FERR
    error_parity_flag_none[0] = 1'b0; // FERR
    error_frame_flag_none[0] = 1'b1; // FERR
end

// ========== Parity mode: EVEN (frame bits: 11) ==========
localparam int NUM_SMOKE_EVEN = 6;
localparam int NUM_RANDOM_EVEN = 9;
localparam int NUM_ERROR_EVEN = 2;
localparam int FRAME_BITS_EVEN = 11;

logic [7:0] smoke_data_even [0:NUM_SMOKE_EVEN-1];
logic [10:0] smoke_frame_even [0:NUM_SMOKE_EVEN-1];

initial begin
    smoke_data_even[0] = 8'h1F; // BASIC_1F
    smoke_frame_even[0] = 11'h63E; // BASIC_1F
    smoke_data_even[1] = 8'h00; // ALL_ZERO
    smoke_frame_even[1] = 11'h400; // ALL_ZERO
    smoke_data_even[2] = 8'h80; // MSB_SET
    smoke_frame_even[2] = 11'h700; // MSB_SET
    smoke_data_even[3] = 8'hFF; // ALL_ONES
    smoke_frame_even[3] = 11'h5FE; // ALL_ONES
    smoke_data_even[4] = 8'h55; // ALT_55
    smoke_frame_even[4] = 11'h4AA; // ALT_55
    smoke_data_even[5] = 8'hAA; // ALT_AA
    smoke_frame_even[5] = 11'h554; // ALT_AA
end

logic [7:0] random_data_even [0:NUM_RANDOM_EVEN-1];
logic [10:0] random_frame_even [0:NUM_RANDOM_EVEN-1];

initial begin
    random_data_even[0] = 8'h2B; // RND_0
    random_frame_even[0] = 11'h456; // RND_0
    random_data_even[1] = 8'h32; // RND_1
    random_frame_even[1] = 11'h664; // RND_1
    random_data_even[2] = 8'hCE; // RND_2
    random_frame_even[2] = 11'h79C; // RND_2
    random_data_even[3] = 8'h10; // RND_3
    random_frame_even[3] = 11'h620; // RND_3
    random_data_even[4] = 8'hB5; // RND_4
    random_frame_even[4] = 11'h76A; // RND_4
    random_data_even[5] = 8'hC2; // RND_5
    random_frame_even[5] = 11'h784; // RND_5
    random_data_even[6] = 8'h63; // RND_6
    random_frame_even[6] = 11'h4C6; // RND_6
    random_data_even[7] = 8'hEF; // RND_7
    random_frame_even[7] = 11'h7DE; // RND_7
    random_data_even[8] = 8'h82; // RND_8
    random_frame_even[8] = 11'h504; // RND_8
end

logic [7:0] error_data_even [0:NUM_ERROR_EVEN-1];
logic [10:0] error_frame_even [0:NUM_ERROR_EVEN-1];
logic error_parity_flag_even [0:NUM_ERROR_EVEN-1];
logic error_frame_flag_even [0:NUM_ERROR_EVEN-1];

initial begin
    error_data_even[0] = 8'h42; // PERR
    error_frame_even[0] = 11'h684; // PERR
    error_parity_flag_even[0] = 1'b1; // PERR
    error_frame_flag_even[0] = 1'b0; // PERR
    error_data_even[1] = 8'h99; // FERR
    error_frame_even[1] = 11'h132; // FERR
    error_parity_flag_even[1] = 1'b0; // FERR
    error_frame_flag_even[1] = 1'b1; // FERR
end

// ========== Parity mode: ODD (frame bits: 11) ==========
localparam int NUM_SMOKE_ODD = 6;
localparam int NUM_RANDOM_ODD = 9;
localparam int NUM_ERROR_ODD = 2;
localparam int FRAME_BITS_ODD = 11;

logic [7:0] smoke_data_odd [0:NUM_SMOKE_ODD-1];
logic [10:0] smoke_frame_odd [0:NUM_SMOKE_ODD-1];

initial begin
    smoke_data_odd[0] = 8'h1F; // BASIC_1F
    smoke_frame_odd[0] = 11'h43E; // BASIC_1F
    smoke_data_odd[1] = 8'h00; // ALL_ZERO
    smoke_frame_odd[1] = 11'h600; // ALL_ZERO
    smoke_data_odd[2] = 8'h80; // MSB_SET
    smoke_frame_odd[2] = 11'h500; // MSB_SET
    smoke_data_odd[3] = 8'hFF; // ALL_ONES
    smoke_frame_odd[3] = 11'h7FE; // ALL_ONES
    smoke_data_odd[4] = 8'h55; // ALT_55
    smoke_frame_odd[4] = 11'h6AA; // ALT_55
    smoke_data_odd[5] = 8'hAA; // ALT_AA
    smoke_frame_odd[5] = 11'h754; // ALT_AA
end

logic [7:0] random_data_odd [0:NUM_RANDOM_ODD-1];
logic [10:0] random_frame_odd [0:NUM_RANDOM_ODD-1];

initial begin
    random_data_odd[0] = 8'h66; // RND_0
    random_frame_odd[0] = 11'h6CC; // RND_0
    random_data_odd[1] = 8'hEB; // RND_1
    random_frame_odd[1] = 11'h7D6; // RND_1
    random_data_odd[2] = 8'h9D; // RND_2
    random_frame_odd[2] = 11'h53A; // RND_2
    random_data_odd[3] = 8'h17; // RND_3
    random_frame_odd[3] = 11'h62E; // RND_3
    random_data_odd[4] = 8'h3B; // RND_4
    random_frame_odd[4] = 11'h476; // RND_4
    random_data_odd[5] = 8'hB2; // RND_5
    random_frame_odd[5] = 11'h764; // RND_5
    random_data_odd[6] = 8'hC2; // RND_6
    random_frame_odd[6] = 11'h584; // RND_6
    random_data_odd[7] = 8'h33; // RND_7
    random_frame_odd[7] = 11'h666; // RND_7
    random_data_odd[8] = 8'hD5; // RND_8
    random_frame_odd[8] = 11'h5AA; // RND_8
end

logic [7:0] error_data_odd [0:NUM_ERROR_ODD-1];
logic [10:0] error_frame_odd [0:NUM_ERROR_ODD-1];
logic error_parity_flag_odd [0:NUM_ERROR_ODD-1];
logic error_frame_flag_odd [0:NUM_ERROR_ODD-1];

initial begin
    error_data_odd[0] = 8'h42; // PERR
    error_frame_odd[0] = 11'h484; // PERR
    error_parity_flag_odd[0] = 1'b1; // PERR
    error_frame_flag_odd[0] = 1'b0; // PERR
    error_data_odd[1] = 8'h99; // FERR
    error_frame_odd[1] = 11'h332; // FERR
    error_parity_flag_odd[1] = 1'b0; // FERR
    error_frame_flag_odd[1] = 1'b1; // FERR
end

`endif // UART_RX_TEST_VECTORS_SVH
